version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: payment-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: openfinance
      MONGO_INITDB_ROOT_PASSWORD: openfinance
      MONGO_INITDB_DATABASE: payments
    volumes:
      - payment_mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  payment_mongodb_data:
